CREATE DATABASE IF NOT EXISTS SHOPNOW_ORDER_MANAGEMENT
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'shopnow'@'localhost' IDENTIFIED BY 'shopnow123';
GRANT ALL PRIVILEGES ON SHOPNOW_ORDER_MANAGEMENT.* TO 'shopnow'@'localhost';
FLUSH PRIVILEGES;

USE SHOPNOW_ORDER_MANAGEMENT;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR(255) NOT NULL UNIQUE,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(12,2) NOT NULL,
    PRODUCT_STATUS VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    WAREHOUSE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    PINCODE VARCHAR(10) NOT NULL,
    CAPACITY INT NOT NULL,
    WAREHOUSE_STATUS VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS INVENTORY (
    INVENTORY_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    STOCK_QUANTITY INT,
    RESERVED_STOCK INT,
    AVAILABLE_STOCK INT,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT UK_INVENTORY_PRODUCT_WAREHOUSE UNIQUE (PRODUCT_ID, WAREHOUSE_ID),
    CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_INVENTORY_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_DATE DATETIME(6) NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    PAYMENT_STATUS VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(12,2) NOT NULL,
    SUBTOTAL DECIMAL(12,2) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    TRANSACTION_ID VARCHAR(255) NOT NULL UNIQUE,
    PAYMENT_METHOD VARCHAR(255) NOT NULL,
    AMOUNT DECIMAL(12,2) NOT NULL,
    PAYMENT_STATUS VARCHAR(50) NOT NULL,
    PAYMENT_DATE DATETIME(6),
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT FK_PAYMENTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE IF NOT EXISTS SHIPMENTS (
    SHIPMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    WAREHOUSE_ID BIGINT NOT NULL,
    TRACKING_NUMBER VARCHAR(255) NOT NULL UNIQUE,
    CARRIER VARCHAR(255) NOT NULL,
    SHIPMENT_STATUS VARCHAR(50) NOT NULL,
    ESTIMATED_DELIVERY_DATE DATE,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT FK_SHIPMENTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_SHIPMENTS_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

CREATE TABLE IF NOT EXISTS RETURN_REQUESTS (
    RETURN_REQUEST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    ORDER_ITEM_ID BIGINT NOT NULL,
    REASON VARCHAR(255) NOT NULL,
    RETURN_STATUS VARCHAR(50) NOT NULL,
    REQUESTED_DATE DATETIME(6) NOT NULL,
    REFUND_AMOUNT DECIMAL(12,2) NOT NULL,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    CONSTRAINT UK_RETURN_REQUEST_ORDER_ITEM UNIQUE (ORDER_ITEM_ID),
    CONSTRAINT FK_RETURN_REQUESTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_RETURN_REQUESTS_ORDER_ITEM FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEMS(ORDER_ITEM_ID)
);

INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE, ADDRESS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'Aarav Shah', 'aarav.shah@shopnow.com', '9876543210', 'Bengaluru, Karnataka', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM CUSTOMERS WHERE EMAIL = 'aarav.shah@shopnow.com'
);

INSERT INTO CUSTOMERS (NAME, EMAIL, PHONE, ADDRESS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'Priya Mehta', 'priya.mehta@shopnow.com', '9876501234', 'Mumbai, Maharashtra', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM CUSTOMERS WHERE EMAIL = 'priya.mehta@shopnow.com'
);

INSERT INTO PRODUCTS (SKU, PRODUCT_NAME, DESCRIPTION, PRICE, PRODUCT_STATUS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'SN-PHONE-001', 'ShopNow SmartPhone', 'Flagship 5G smartphone', 599.99, 'ACTIVE', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM PRODUCTS WHERE SKU = 'SN-PHONE-001'
);

INSERT INTO PRODUCTS (SKU, PRODUCT_NAME, DESCRIPTION, PRICE, PRODUCT_STATUS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'SN-LAP-002', 'ShopNow Laptop', '14 inch business laptop', 1099.00, 'ACTIVE', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM PRODUCTS WHERE SKU = 'SN-LAP-002'
);

INSERT INTO PRODUCTS (SKU, PRODUCT_NAME, DESCRIPTION, PRICE, PRODUCT_STATUS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'SN-EARBUD-003', 'ShopNow Earbuds', 'Wireless noise-cancelling earbuds', 129.00, 'ACTIVE', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM PRODUCTS WHERE SKU = 'SN-EARBUD-003'
);

INSERT INTO WAREHOUSES (WAREHOUSE_NAME, LOCATION, PINCODE, CAPACITY, WAREHOUSE_STATUS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'Bengaluru FC', 'Bengaluru', '560001', 1000, 'ACTIVE', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM WAREHOUSES WHERE WAREHOUSE_NAME = 'Bengaluru FC'
);

INSERT INTO WAREHOUSES (WAREHOUSE_NAME, LOCATION, PINCODE, CAPACITY, WAREHOUSE_STATUS, CREATED_AT, UPDATED_AT)
SELECT * FROM (
    SELECT 'Mumbai FC', 'Mumbai', '400001', 1200, 'ACTIVE', NOW(6), NOW(6)
) AS tmp
WHERE NOT EXISTS (
    SELECT 1 FROM WAREHOUSES WHERE WAREHOUSE_NAME = 'Mumbai FC'
);

INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, STOCK_QUANTITY, RESERVED_STOCK, AVAILABLE_STOCK, CREATED_AT, UPDATED_AT)
SELECT p.PRODUCT_ID, w.WAREHOUSE_ID, 150, 0, 150, NOW(6), NOW(6)
FROM PRODUCTS p
JOIN WAREHOUSES w ON w.WAREHOUSE_NAME = 'Bengaluru FC'
WHERE p.SKU = 'SN-PHONE-001'
  AND NOT EXISTS (
      SELECT 1 FROM INVENTORY i
      WHERE i.PRODUCT_ID = p.PRODUCT_ID AND i.WAREHOUSE_ID = w.WAREHOUSE_ID
  );

INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, STOCK_QUANTITY, RESERVED_STOCK, AVAILABLE_STOCK, CREATED_AT, UPDATED_AT)
SELECT p.PRODUCT_ID, w.WAREHOUSE_ID, 80, 0, 80, NOW(6), NOW(6)
FROM PRODUCTS p
JOIN WAREHOUSES w ON w.WAREHOUSE_NAME = 'Bengaluru FC'
WHERE p.SKU = 'SN-LAP-002'
  AND NOT EXISTS (
      SELECT 1 FROM INVENTORY i
      WHERE i.PRODUCT_ID = p.PRODUCT_ID AND i.WAREHOUSE_ID = w.WAREHOUSE_ID
  );

INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, STOCK_QUANTITY, RESERVED_STOCK, AVAILABLE_STOCK, CREATED_AT, UPDATED_AT)
SELECT p.PRODUCT_ID, w.WAREHOUSE_ID, 200, 0, 200, NOW(6), NOW(6)
FROM PRODUCTS p
JOIN WAREHOUSES w ON w.WAREHOUSE_NAME = 'Mumbai FC'
WHERE p.SKU = 'SN-EARBUD-003'
  AND NOT EXISTS (
      SELECT 1 FROM INVENTORY i
      WHERE i.PRODUCT_ID = p.PRODUCT_ID AND i.WAREHOUSE_ID = w.WAREHOUSE_ID
  );
