replicaCount: 1

image:
  repository: shopnow-order-management
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

app:
  serverPort: 8080
  datasourceUrl: jdbc:mysql://mysql:3306/SHOPNOW_ORDER_MANAGEMENT?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  shippingCarrierUrl: http://shipping-carrier:9091
  paymentGatewayUrl: http://payment-gateway:9092
  jwtExpirationSeconds: 86400

secrets:
  databaseUsername: root
  databasePassword: vision@123
  appUsername: shopnow-admin
  appPassword: shopnow123
  jwtSecret: U2hvcE5vd0p3dFNlY3JldEtleUZvckxvY2FsRGV2RW52aXJvbm1lbnQxMjM0NTY3ODkw

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: shopnow.local
      paths:
        - path: /
          pathType: Prefix

livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 60
  periodSeconds: 20

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 15
