apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopnow-order-management.fullname" . }}-config
data:
  SERVER_PORT: {{ .Values.app.serverPort | quote }}
  SHOPNOW_DB_URL: {{ .Values.app.datasourceUrl | quote }}
  SHIPPING_CARRIER_URL: {{ .Values.app.shippingCarrierUrl | quote }}
  PAYMENT_GATEWAY_URL: {{ .Values.app.paymentGatewayUrl | quote }}
  SHOPNOW_JWT_EXPIRATION_SECONDS: {{ .Values.app.jwtExpirationSeconds | quote }}
